Add 1.0 Docker images, and upgrade all the images to follow the Quick Starts for each language.
grpc/grpc-docker-library pull request #37
Opened 2016-09-26 21:34 UTC by markmandel

I updated the language version for each one as well to what is latest.

I was tempted to remove the onbuild images - simply because they expanded the support required, but I updated the version numbers they depended on and left them in. Let me know your thoughts.

Please let me know if there is any adjustment / refinement you would like to see.

2016-09-27 15:26 UTC, nathanielmanistaatgoogle requested changes

2016-09-27 15:26 UTC, nathanielmanistaatgoogle commented on 1.0/python/README.md
> +This is the official docker image for the Python facility of grpc.  For an
gRPC when written in prose should always be styled as "gRPC".

2016-09-27 15:26 UTC, nathanielmanistaatgoogle commented on 1.0/python/README.md
> +overview and usage examples, see the grpc python documentation.
Styling here should be "gRPC Python".

2016-09-27 15:26 UTC, nathanielmanistaatgoogle commented on 1.0/python/Dockerfile
> +RUN pip install grpcio==${GRPC_PYTHON_VERSION} grpcio-tools==${GRPC_PYTHON_VERSION}
Missing newline at end-of-file (here and in at least one other file in this pull request).

2016-09-27 18:47 UTC, markmandel commented
Updated the Dockerfiles so that they all have linebreaks, and fixed up all the readme's in the `1.0` folder such that they state "gRPC" (worth nothing that in `0.10` and `0.11` folders, they are still "grpc")

Please let me know if you have any further feedback.

2016-09-27 21:09 UTC, nathanielmanistaatgoogle commented on 1.0/python/README.md
> +overview and usage examples, see the gRPC python documentation.
"gRPC Python" on this line too.

2016-09-27 21:10 UTC, nathanielmanistaatgoogle commented
I was just jumping on some cosmetic stuff; @nicolasnoble will be the reviewer of substance for this change (or he will route this change to someone else who will be).

2016-09-27 21:13 UTC, markmandel commented
No worries. Good catches. Fixed up now. :+1:

2016-10-05 05:52 UTC, nicolasnoble requested changes
One tiny nit, otherwise lgtm.

2016-10-05 05:52 UTC, nicolasnoble commented on 1.0/cxx/Dockerfile
> +    make && make install && make clean
Missing end of line.

2016-10-05 21:02 UTC, markmandel commented
Added newline. Let me know if you would like a rebase to clean up the commit history or not :smiley:

2016-10-05 21:04 UTC, nathanielmanistaatgoogle commented
I favor this squashing; @nicolasnoble will be the one to actually decide.

2016-10-12 15:48 UTC, markmandel commented
@nicolasnoble What do you reckon? Shall I squash it, and then it can be merged? :smile:

2016-10-13 23:33 UTC, nicolasnoble approved these changes

2016-10-13 23:33 UTC, nicolasnoble commented
I don't really care either way - that repository has less importance when it comes to history, so squash, don't squash, do what you prefer :)

2016-10-13 23:35 UTC, markmandel commented
@nathanielmanistaatgoogle Do you feel strongly either way? I don't mind. I just want to get this through the door? :smile:

2016-10-14 00:45 UTC, nathanielmanistaatgoogle commented
Squash.

2016-10-14 00:57 UTC, nathanielmanistaatgoogle commented
Also for extra bonus points adhere to [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules).

2016-10-14 18:59 UTC, markmandel commented
@nathanielmanistaatgoogle Squashed and updated the commit message.

(Love that guideline. Stealing for future use)

2016-10-14 19:32 UTC, nathanielmanistaatgoogle approved these changes

2016-10-14 19:32 UTC, merged

2016-10-14 19:40 UTC, markmandel commented
Thank you!