Update CXX to 1.12.0 release.
grpc/grpc-docker-library pull request #56
Opened 2018-06-03 22:27 UTC by markmandel

2018-06-05 15:18 UTC, mcos commented
This looks great. Is there a chance you could update the other languages to the same version (we're dependent on the php, python and go images, specifically)? Thanks either way.

2018-06-05 15:24 UTC, markmandel commented
@mcos if you want to submit PRs, and get the approved, I can get the images up on Dockerhub.

2018-06-05 15:28 UTC, mcos commented
cool. I can make some as soon as i have some time. cheers.

2018-06-06 15:47 UTC, markmandel commented
Gentle bump, can I get an approval on this PR?

2018-06-07 04:39 UTC, nathanielmanistaatgoogle requested changes

2018-06-07 04:39 UTC, nathanielmanistaatgoogle commented on 1.12.0/cxx/Dockerfile
> +# Copyright 2017 gRPC authors.
Copied from one of last year's sources?

2018-06-07 05:09 UTC, markmandel commented on 1.12.0/cxx/Dockerfile
> +# Copyright 2017 gRPC authors.
Fixed!

2018-06-07 15:36 UTC, nathanielmanistaatgoogle approved these changes

2018-06-08 15:47 UTC, markmandel commented
Coming back to this - any blocking issues on getting this merged?

2018-06-11 20:35 UTC, nicolasnoble approved these changes

2018-06-11 20:35 UTC, merged

2018-06-12 00:05 UTC, markmandel commented
Thank you - build is currently in queue:
https://hub.docker.com/r/grpc/cxx/builds/